import Head from "next/head";

const Title = () => {
  return (
    <Head>
      <title>Staking Contract</title>
      <meta
        name="description"
        content="Smart Contract script generated by Aiken"
      />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Title;
